export enum ErrorCode {
  //User
  USER_EMAIL_ALREADY_EXIST = 'U001',
  USER_NICKNAME_ALREADY_EXIST = 'U002',
  USER_NOT_FOUND = 'U003',
  USER_INVALID_PASSWROD = 'U004',
  USER_INVALID_PROVINCE = 'U005',
  USER_INVALID_CITY = 'U006',

  //Board
  BOARD_NOT_FOUND = 'B001',

  //Image
  IMAGE_NOT_FOUND = 'I001',
  IMAGE_SERVICE_CONFIGURATION_ERROR = 'I002',
  IMAGE_UPLOAD_FAILED = 'I003',
}
