export enum ErrorCode {

    //User
    USER_ACCOUNTID_ALREADY_EXIST = 'U001',
    USER_NICKNAME_ALREADY_EXIST = 'U002',
    USER_NOT_FOUND = 'U003',
    USER_INVALID_PASSWROD = 'U004',
    USER_INVALID_PROVINCE = 'U005',
    USER_INVALID_CITY = 'U006',

    //Board
    BOARD_NOT_FOUND = 'B001',
    
    //pagination
    PAGE_NOT_EXIST = 'P001',
}